emptySet = set()
emptySet.add(input("enter no. that you want to add in the set :"))
emptySet.add(input("enter no. that you want to add in the set :"))
emptySet.add(input("enter no. that you want to add in the set :"))
emptySet.add(input("enter no. that you want to add in the set :"))
emptySet.add(input("enter no. that you want to add in the set :"))
emptySet.add(input("enter no. that you want to add in the set :"))
emptySet.add(input("enter no. that you want to add in the set :"))
emptySet.add(input("enter no. that you want to add in the set :"))

print(emptySet)